name: Upload Get-File Lambda

on:
  push:
    branches:
      - main
      - develop
    paths:
      - get_file/**
      - utils/**
      - .github/workflows/build.get-file.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch
        id: tags
        run: |
          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
            echo "function=get-file" >> $GITHUB_OUTPUT
            echo "function-cache=get-file-cache" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == "refs/heads/develop" ]]; then
            echo "function=get-file-dev" >> $GITHUB_OUTPUT
            echo "function-cache=get-file-cache-dev" >> $GITHUB_OUTPUT
          else
            echo "Branch not supported"
            exit 1
          fi
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: zip lambda
        run: zip -r lambda.zip get_file utils
      - name: Deploy AWS Lambda function
        uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          package: lambda.zip
          function-name: ${{ steps.tags.outputs.function }}
          AWS_REGION: us-east-1
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy AWS Lambda function
        uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          package: lambda.zip
          function-name: ${{ steps.tags.outputs.function-cache }}
          AWS_REGION: us-east-1
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to S3 prod account
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1
          aws-bucket: opmed-tf
          file-path: get-file.zip
          destination-dir: /
          bucket-root: /
      - name: Deploy AWS Lambda function to prod account
        uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          package: lambda.zip
          function-name: ${{ steps.tags.outputs.function }}
          AWS_REGION: us-east-1
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}