name: Upload Lambda

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install --no-cache-dir --no-binary :all: --no-deps -r requirements.txt -t .
    - name: zip lambda
      run: zip -r lambda.zip *
    - name: Deploy AWS Lambda function
      uses: yvesgurcan/deploy-lambda-function@v0.0.5
      with:
        package: lambda.zip
        function-name: fetch-data-dev
        AWS_REGION: us-east-1
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}