# coding: utf-8

"""
    GreatMix Planner API

    The API for the Planner  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401




class TimeModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'start': 'datetime',
        'end': 'datetime',
        'resource_id': 'str',
        'room_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'start': 'start',
        'end': 'end',
        'resource_id': 'resourceId',
        'room_id': 'roomId'
    }

    def __init__(self, id=None, start=None, end=None, resource_id=None, room_id=None):  # noqa: E501
        """TimeModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._start = None
        self._end = None
        self._resource_id = None
        self._room_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if start is not None:
            self.start = start
        if end is not None:
            self.end = end
        if resource_id is not None:
            self.resource_id = resource_id
        if room_id is not None:
            self.room_id = room_id

    @property
    def id(self):
        """Gets the id of this TimeModel.  # noqa: E501


        :return: The id of this TimeModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TimeModel.


        :param id: The id of this TimeModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def start(self):
        """Gets the start of this TimeModel.  # noqa: E501


        :return: The start of this TimeModel.  # noqa: E501
        :rtype: datetime
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this TimeModel.


        :param start: The start of this TimeModel.  # noqa: E501
        :type: datetime
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this TimeModel.  # noqa: E501


        :return: The end of this TimeModel.  # noqa: E501
        :rtype: datetime
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this TimeModel.


        :param end: The end of this TimeModel.  # noqa: E501
        :type: datetime
        """

        self._end = end

    @property
    def resource_id(self):
        """Gets the resource_id of this TimeModel.  # noqa: E501


        :return: The resource_id of this TimeModel.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this TimeModel.


        :param resource_id: The resource_id of this TimeModel.  # noqa: E501
        :type: str
        """

        self._resource_id = resource_id

    @property
    def room_id(self):
        """Gets the room_id of this TimeModel.  # noqa: E501


        :return: The room_id of this TimeModel.  # noqa: E501
        :rtype: int
        """
        return self._room_id

    @room_id.setter
    def room_id(self, room_id):
        """Sets the room_id of this TimeModel.


        :param room_id: The room_id of this TimeModel.  # noqa: E501
        :type: int
        """

        self._room_id = room_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
